name: Stale PR Report

on:
  schedule:
  - cron:  '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
    - name: Send Report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SENDGRID_SERVER: smtp.sendgrid.net
        SENDGRID_FROM: Puppet Community Team
        SENDGRID_ADDRESS: puppetlabseducation@puppetlabs.com
        SENDGRID_DOMAIN: puppetlabs.com
        SENDGRID_USERNAME: puppetlabseducation
        SENDGRID_PASSWORD: ${{ secrets.SENDGRID_PASSWORD }}
        EMAIL_ADDRESS: ben.ford@puppet.com
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake stale_pulls
        
