name: Stale PR Report

on:
  schedule:
  - cron:  '0/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
    - name: Send Report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SENDGRID_SERVER: ${{ secrets.SENDGRID_SERVER }}
        SENDGRID_ADDRESS: ${{ secrets.SENDGRID_ADDRESS }}
        SENDGRID_DOMAIN: ${{ secrets.SENDGRID_DOMAIN }}
        SENDGRID_USERNAME: ${{ secrets.SENDGRID_USERNAME }}
        SENDGRID_PASSWORD: ${{ secrets.SENDGRID_PASSWORD }}
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake stale_pulls
        
